name: CI

on:
  push:
    branches:
      - main  # Ou troque por "master" se sua branch principal for master

jobs:
  build-deploy:

    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: Install Zola
      run: |
        curl -s -L https://github.com/getzola/zola/releases/download/v0.14.0/zola-v0.14.0-x86_64-unknown-linux-gnu.tar.gz | tar zx
        sudo mv zola /usr/local/bin/

    - name: Build
      run: zola build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .

